### ISSUE TITLE
all blocks without drop tag missing some

### ISSUE THREAD

**Issue by RoarkCats** [PixiGeko/Minecraft-generated-data#10]
Don't things like barriers and bedrock count too? or is the tag only for things minable in survival or something?

**Comment by PixiGeko** [comment]
It seems to be only for blocks that can be broken by the player in survival, but that's not really intentional. I'll fix this and update previous versions soon, thank you !

**Comment by PixiGeko** [comment]
I'm not sure it's a good idea to actually put all blocks without drop, if I use the list of all blocks available in game then the file “all_blocks_without_drop.json” also contains all blocks without loot table, like for example the wall version of signs, banners etc. I think I'll leave the file as it is, but if you really need a tag with ALL the blocks I can add a new file for it

[all_blocks_without_drop_but_really_all_blocks.json](https://github.com/PixiGeko/Minecraft-generated-data/files/15176771/all_blocks_without_drop_but_really_all_blocks.json)

**Comment by RoarkCats** [comment]
Interesting, thanks for the list, not sure if others will want it or not, but maybe a rename or note might be in order for the existing file? It is pretty obvious that it's survival blocks, but the name is a tad misleading

**Comment by PixiGeko** [comment]
Yep good idea, I'm updating all the versions with this: 

`all_blocks_without_drop.json` = all (really all) blocks without drops
`all_survival_blocks_without_drop.json` = all blocks with a loot table but no drop (= previously `all_blocks_without_drop.json`)
`all_entities_without_drop.json` = all (really all) entities without drops
`all_living_entities_without_drop.json` = all entities with a loot table (living entities) but no drop (= previously `all_entities_without_drop.json`)

There was the same issue with the entities
